-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.11.2-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.10.0.7000
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for DB_V2_TMS_LABEL_PRINT_WEB
CREATE DATABASE IF NOT EXISTS `DB_V2_TMS_LABEL_PRINT_WEB` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `DB_V2_TMS_LABEL_PRINT_WEB`;

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.DEPARTMENT
CREATE TABLE IF NOT EXISTS `DEPARTMENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FACTORYID` varchar(50) NOT NULL,
  `DEPARTMENTID` varchar(50) NOT NULL,
  `EVENTUSER` varchar(255) NOT NULL,
  `EVENTTIME` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `Index 3` (`FACTORYID`,`DEPARTMENTID`) USING BTREE,
  CONSTRAINT `FK_DEPARTMENT_FACTORY` FOREIGN KEY (`FACTORYID`) REFERENCES `factory` (`FACTORYID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data exporting was unselected.

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.FACTORY
CREATE TABLE IF NOT EXISTS `FACTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FACTORYID` varchar(50) NOT NULL,
  `DESCRIPTION` text DEFAULT NULL,
  `EVENTUSER` varchar(50) DEFAULT NULL,
  `EVENTTIME` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID`),
  UNIQUE KEY `FACTORYID` (`FACTORYID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data exporting was unselected.

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.MODELSPEC
CREATE TABLE IF NOT EXISTS `MODELSPEC` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MODELID` varchar(10) NOT NULL,
  `MATERIALSCODE` varchar(50) NOT NULL,
  `PRODUCT` varchar(50) NOT NULL,
  `PRODUCTFACTORY` varchar(50) NOT NULL,
  `SUPPLIER` varchar(50) NOT NULL,
  `DESCRIPTION` text DEFAULT NULL,
  `EVENTUSER` varchar(50) NOT NULL,
  `EVENTTIME` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `MODELID` (`MODELID`),
  KEY `FK_MODELSPEC_FACTORY` (`PRODUCTFACTORY`),
  CONSTRAINT `FK_MODELSPEC_FACTORY` FOREIGN KEY (`PRODUCTFACTORY`) REFERENCES `FACTORY` (`FACTORYID`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data exporting was unselected.

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.MODELSPEC_HISTORY
CREATE TABLE IF NOT EXISTS `MODELSPEC_HISTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MODELID` varchar(10) NOT NULL,
  `MATERIALSCODE` varchar(50) NOT NULL,
  `PRODUCT` varchar(50) NOT NULL,
  `PRODUCTFACTORY` varchar(50) NOT NULL,
  `SUPPLIER` varchar(50) NOT NULL,
  `DESCRIPTION` text DEFAULT NULL,
  `EVENTUSER` varchar(50) NOT NULL,
  `EVENTTIME` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data exporting was unselected.

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.PACKING
CREATE TABLE IF NOT EXISTS `PACKING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MODELID` varchar(50) NOT NULL COMMENT 'model id ',
  `BOXLABEL_QR` varchar(26) NOT NULL COMMENT 'thông tin qr tray label',
  `QUANTITY` int(11) NOT NULL COMMENT 'số lượng /inner ',
  `REMARKS` varchar(250) DEFAULT NULL COMMENT 'partron part name',
  `LOTNO` varchar(50) NOT NULL COMMENT 'Lot No',
  `EXPIRATIONDATE` date NOT NULL COMMENT 'Expiration date ',
  `EVENTUSER` varchar(50) NOT NULL COMMENT 'người thao tác packing',
  `EVENTTIME` datetime NOT NULL COMMENT 'thời gian thao tác packing',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `BOX_QR` (`BOXLABEL_QR`) USING BTREE,
  UNIQUE KEY `LOT_NO` (`LOTNO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Data exporting was unselected.

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.REPRINT_HISTORY
CREATE TABLE IF NOT EXISTS `REPRINT_HISTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LABELTYPE` enum('OUTBOX') NOT NULL,
  `LABELCODE` varchar(100) NOT NULL,
  `EVENTUSER` varchar(30) NOT NULL,
  `EVENTTIME` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `IDX_LABELTYPE_CODE` (`LABELTYPE`,`LABELCODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data exporting was unselected.

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.ROLE
CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLEID` varchar(50) NOT NULL,
  `DESCRIPTION` text DEFAULT NULL,
  `EVENTUSER` varchar(50) NOT NULL,
  `EVENTTIME` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `ROLEID` (`ROLEID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

-- Data exporting was unselected.

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.TRANSLATIONS
CREATE TABLE IF NOT EXISTS `TRANSLATIONS` (
  `ID` varchar(50) NOT NULL,
  `EN` text DEFAULT NULL,
  `VI` text DEFAULT NULL,
  `KR` text DEFAULT NULL,
  `DESCRIPTION` text NOT NULL,
  `EVENTTIME` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `EVENTUSER` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `description` (`DESCRIPTION`) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data exporting was unselected.

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.USER
CREATE TABLE IF NOT EXISTS `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERID` varchar(255) NOT NULL COMMENT 'mail',
  `PASSWORD` varchar(255) NOT NULL,
  `FULLNAME` text DEFAULT NULL,
  `ROLEID` varchar(50) NOT NULL,
  `STATUS` enum('Active','Inactive') DEFAULT 'Active',
  `FACTORYID` varchar(50) DEFAULT NULL,
  `DEPARTMENTID` varchar(50) DEFAULT NULL,
  `EVENTUSER` varchar(50) NOT NULL DEFAULT '',
  `EVENTTIME` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE KEY `USERID` (`USERID`) USING BTREE,
  KEY `FK_USER_ROLE` (`ROLEID`) USING BTREE,
  KEY `FACTORYID` (`FACTORYID`),
  KEY `DEPARTMENTID` (`DEPARTMENTID`),
  KEY `FK_USER_DEPARTMENT` (`FACTORYID`,`DEPARTMENTID`),
  CONSTRAINT `FK_USER_DEPARTMENT` FOREIGN KEY (`FACTORYID`, `DEPARTMENTID`) REFERENCES `department` (`FACTORYID`, `DEPARTMENTID`) ON DELETE CASCADE,
  CONSTRAINT `FK_USER_ROLE` FOREIGN KEY (`ROLEID`) REFERENCES `role` (`ROLEID`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data exporting was unselected.

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.ZPLSPEC
CREATE TABLE IF NOT EXISTS `ZPLSPEC` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ZPLTYPE` varchar(50) NOT NULL,
  `ZPLDENSITY` enum('203DPI','300DPI') NOT NULL DEFAULT '203DPI',
  `ZPLCODE` text NOT NULL,
  `EVENTUSER` text NOT NULL,
  `EVENTTIME` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data exporting was unselected.

-- Dumping structure for table DB_V2_TMS_LABEL_PRINT_WEB.ZPLSPEC_HISTORY
CREATE TABLE IF NOT EXISTS `ZPLSPEC_HISTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ZPLTYPE` varchar(50) NOT NULL,
  `ZPLDENSITY` enum('203DPI','300DPI') NOT NULL DEFAULT '203DPI',
  `ZPLCODE` text NOT NULL,
  `EVENTUSER` text NOT NULL,
  `EVENTTIME` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data exporting was unselected.

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
